/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 8, 2019 at 1:24:42 PM Eastern European Standard Time
* Operating System: Version 12.1 (Build 16B92)
* Image Source: /System/Library/Frameworks/AVFoundation.framework/AVFoundation
* classdump-dyld is licensed under GPLv3, Copyright Â© 2013-2016 by Elias Limneos.
*/

@interface AVFlashlight : NSObject 
-(BOOL)setFlashlightLevel:(float)arg1 withError:(id*)arg2 ;
@end

static AVFlashlight *fleshilght;
static BOOL flashlightEnabled = NO;

void toggleFlashlight() 
{

    [fleshilght setFlashlightLevel: flashlightEnabled ? 0 : 1 withError:nil];
    flashlightEnabled = !flashlightEnabled;

}

%hook UIWindow

- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent *)event
{
    %orig;
    if(event.type == UIEventSubtypeMotionShake && self == [[UIApplication sharedApplication] keyWindow])
    {
        toggleFlashlight();
    }
}

%end

%ctor 
{
	fleshilght = [[AVFlashlight alloc] init];
}
